# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13201fe4739cc9d2097d79ac1a08858bfee054b417997137cba07b610fdc68d3c0849146bac1401c534e266b74052f860fcb2ad13026ab6d9d17eda5c0351f9b

test:
  secret_key_base: 7038dcf11effef4f0c697f780a6e4c5b22e618e2d088df8596be839e61ecd058b2240f74f17fc6eb5872ef9498bef6e707e2cdcbffec3bf0b11160afdaa9ba89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
